import './global.css';
import './styles/room.scss';
import './query.css?query';
import styles from "/Users/jiangwei/projects/tswc/fixtures/package-a/dist/css.module.css";
import vite from "/Users/jiangwei/projects/tswc/fixtures/package-a/dist/vite.svg";
import { name } from "/Users/jiangwei/projects/tswc/fixtures/package-a/dist/package-b/src/index.ts";
import { table } from "/Users/jiangwei/projects/tswc/fixtures/package-a/dist/node_modules/.pnpm/functional-md@1.1.0/node_modules/functional-md/lib/index.js";
import * as reexport from "/Users/jiangwei/projects/tswc/fixtures/package-a/dist/re-export.ts";
import { Button } from "/Users/jiangwei/projects/tswc/fixtures/package-a/dist/node_modules/.pnpm/@mui+material@5.16.7_@types+react@18.3.12_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/@mui/material/Button/index.js";
import { IconButton } from "/Users/jiangwei/projects/tswc/fixtures/package-a/dist/node_modules/.pnpm/@mui+material@5.16.7_@types+react@18.3.12_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/@mui/material/IconButton/index.js";
console.log(Button, IconButton);
console.log(styles, vite);
console.log(name);
console.log(table);
const a = 1;
export { reexport } from "";
export default a;
export { another } from "";
